### ISSUE TITLE
Groovy API: Missing endpoints / sort params

### ISSUE THREAD

**Issue by alexejFroebel** [OpusCapita/pim-integrations-groovy-api#29]

**Comment by alexejFroebel** [comment]
PR: https://github.com/OpusCapita/pim-integrations-groovy-api/pull/30

**Comment by alexejFroebel** [comment]
Note: YOu need to update pit after this is released(dependency in pit and release)

**Comment by DavidBrien** [comment]
code review done!

**Comment by DavidBrien** [comment]
QA done
