### ISSUE TITLE
Nullpointer Exception

### ISSUE THREAD

**Issue by alexejFroebel** [OpusCapita/pim-integrations-groovy-api#32]
IFM says:
getProduct() 
Fehler java.lang.NullPointerException: Cannot invoke method join() on null object 
wenn Parameter languageIds, exclude und include nicht angegeben werden 

- [x] Try to reproduce it
- [x] If reproduceable: Fix it

**Comment by alexejFroebel** [comment]
PR: #35

**Comment by UweStolz** [comment]
QA: Done, no findings
