### ISSUE TITLE
Params not useable

### ISSUE THREAD

**Issue by alexejFroebel** [OpusCapita/pim-integrations-groovy-api#33]
IFM says:
getProductAttributeValues() 
In Groovy sind die in REST vorhandenen Parameter variantId und languageIds nicht nutzbar 

- [x] Try to reproduce it
- [x] If reproduceable: Fix it

**Comment by alexejFroebel** [comment]
PR: #34

**Comment by UweStolz** [comment]
### QA:

---

**Testsystems**: 
- [PIM2](http://fn-pim2.westeurope.cloudapp.azure.com/pim/)
- [PIT:5001](http://fn-pit.westeurope.cloudapp.azure.com:5001/pit/)


ASUS ZenPad 10 TriCover
ID: 90XB015P-BSL3M0


- Keine sprache am attribut, Variante gegeben
-> Filtern nach Sprache "en" & Variante "90XB015P-BSL3M0-119"
= Attribut wird ausgegeben


- Sprache "en" am attribut, Variante gegeben
-> Filtern nach Sprache "en" & Variante "90XB015P-BSL3M0-119"
= attribut wird **nicht** ausgegeben

**Code**:
~~~
import grails.util.Holders

ctx = Holders.applicationContext

def api = ctx.customizationService.pimApi().initialize("http://fn-pit.westeurope.cloudapp.azure.com:5001", "ff48f7b4-0c14-473b-ae07-e352a3c47d57")

try {
    def options = [languageIds: "en", variantId: "90XB015P-BSL3M0-119"]
    def result = api.getProductAttributeValues("MasterCatalog", "90XB015P-BSL3M0", options)
    println result.getValue()
} catch (Exception e) {
    println e
}
~~~

**Comment by alexejFroebel** [comment]
The first problem is no problem: its expected behaviour

**Comment by alexejFroebel** [comment]
You used the wrong script, you need to use languageIds with ["en"]
